// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorklog(arg1, arg2) {
  return window['go']['jira']['JiraInstance']['AddWorklog'](arg1, arg2);
}

export function GetAssignedIssues() {
  return window['go']['jira']['JiraInstance']['GetAssignedIssues']();
}

export function GetBaseUrl() {
  return window['go']['jira']['JiraInstance']['GetBaseUrl']();
}

export function GetCurrentTimerValue(arg1) {
  return window['go']['jira']['JiraInstance']['GetCurrentTimerValue'](arg1);
}

export function GetWorkLogs(arg1) {
  return window['go']['jira']['JiraInstance']['GetWorkLogs'](arg1);
}

export function LogDebug(arg1) {
  return window['go']['jira']['JiraInstance']['LogDebug'](arg1);
}

export function LogDebugf(arg1, arg2) {
  return window['go']['jira']['JiraInstance']['LogDebugf'](arg1, arg2);
}

export function LogWarning(arg1) {
  return window['go']['jira']['JiraInstance']['LogWarning'](arg1);
}

export function LogWarningf(arg1, arg2) {
  return window['go']['jira']['JiraInstance']['LogWarningf'](arg1, arg2);
}

export function PauseTimer(arg1) {
  return window['go']['jira']['JiraInstance']['PauseTimer'](arg1);
}

export function ResetTimer(arg1) {
  return window['go']['jira']['JiraInstance']['ResetTimer'](arg1);
}

export function StartTimer(arg1) {
  return window['go']['jira']['JiraInstance']['StartTimer'](arg1);
}

export function SubmitWorklog(arg1) {
  return window['go']['jira']['JiraInstance']['SubmitWorklog'](arg1);
}
