// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssignedIssues() {
  return window['go']['jira']['JiraInstance']['GetAssignedIssues']();
}

export function GetBaseUrl() {
  return window['go']['jira']['JiraInstance']['GetBaseUrl']();
}

export function GetTimeSpentOnIssue(arg1) {
  return window['go']['jira']['JiraInstance']['GetTimeSpentOnIssue'](arg1);
}

export function GetWorkLogs(arg1) {
  return window['go']['jira']['JiraInstance']['GetWorkLogs'](arg1);
}

export function SubmitWorklfowLogs(arg1, arg2) {
  return window['go']['jira']['JiraInstance']['SubmitWorklfowLogs'](arg1, arg2);
}
