// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jira} from '../models';

export function GetAssignedIssues():Promise<Array<jira.Issue>>;

export function GetBaseUrl():Promise<string>;

export function GetTimeSpentOnIssue(arg1:string):Promise<string>;

export function GetWorkLogs(arg1:string):Promise<Array<jira.Worklog>>;

export function SubmitWorklfowLogs(arg1:string,arg2:number):Promise<void>;
